spring:
 application:
  name: Prod-Config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    fetch-registry: true
    registerWithEureka: true
